version: '3.9'
services:
  app:
    build:
      context: ./
      # dockerfile: Dockerfile
      shm_size: '5gb'

    container_name: 'home-credit-default-risk'
    # devices:
    #   - /dev/nvidia0
    working_dir: '/workspace'
    volumes:
      -  ./:/workspace/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "127.0.0.1:8080:8888"
    tty: true
    networks:
      - db_network

networks:
  db_network:
    external: true